version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  bot:
    build: .
    container_name: pumpbot
    restart: always
    env_file: .env
    depends_on:
      - mongodb

volumes:
  mongo-data:
