version: '3.8'

services:
  app:
    image: ghcr.io/matborgeaud/pump-fun-bot:latest
    container_name: pump_fun_app
    restart: always
    environment:
      API_FETCH_INTERVAL: ${API_FETCH_INTERVAL}
      DATA_RETENTION_HOURS: ${DATA_RETENTION_HOURS}
      ALERT_DUPLICATE_THRESHOLD: ${ALERT_DUPLICATE_THRESHOLD}
      API_URL: ${API_URL}
      MONGO_URI: ${MONGO_URI}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      PORT: ${PORT}
    depends_on:
      - mongo
    networks:
      - app_network
    ports:
      - "${PORT}:${PORT}"

  mongo:
    image: mongo:latest
    container_name: pump_fun_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - app_network

  mongo-express:
    image: mongo-express:latest
    container_name: pump_fun_mongo_express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    depends_on:
      - mongo
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network: