version: '3.8'

services:
  app:
    image: github.com/matborgeaud/pump-fun-bot:latest # Utiliser GitHub Container Registry
    container_name: pump_fun_app
    restart: always
    env_file: .env
    depends_on:
      - mongo
    networks:
      - app_network

  mongo:
    image: mongo:latest
    container_name: pump_fun_mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
