version: '3.8'

services:
  app:
    image: ghcr.io/matborgeaud/pump-fun-bot:latest
    container_name: pump_fun_app
    restart: always
    environment:
      API_FETCH_INTERVAL: ${API_FETCH_INTERVAL}
      DATA_RETENTION_HOURS: ${DATA_RETENTION_HOURS}
      ALERT_DUPLICATE_THRESHOLD: ${ALERT_DUPLICATE_THRESHOLD}
      API_URL: ${API_URL}
      MONGO_URI: ${MONGO_URI}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      PORT: ${PORT}
    depends_on:
      - mongo
    networks:
      - app_network
    ports:
      - "${PORT}:${PORT}"

  mongo:
    image: mongo:latest
    container_name: pump_fun_mongo
    restart: always  
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network


volumes:
  mongo_data:

networks:
  app_network: